### ISSUE TITLE
the dotfiles dont work anymore

### ISSUE THREAD

**Issue by reze-dev** [ohxxm/espresso#1]
I tried installing and the dotfiles was installed successfully but they don't work anymore.
When I login i get the default awesome with a giant error message.

**Comment by reze-dev** [comment]
![Screenshot_nixos_2023-12-10_00:41:11](https://github.com/Spaxly/espresso/assets/25588579/fe1446fe-1b35-4f15-b7ad-c795700439b8)

**Comment by ohxxm** [comment]
You have to download the modules by using the terminal. Try the following commands:

`cd ~/.config/awesome`
`git clone https://github.com/andOrlando/color`
`git clone https://github.com/andOrlando/bling`
`git clone https://github.com/andOrlando/rubato`

**Comment by reze-dev** [comment]
Hi This repo "git clone https://github.com/andOrlando/bling" doesn't exist anymore. I downloaded other two repos to my ~/.config/awesome directory. it still doesn't work.

**Comment by atomiksan** [comment]
Closing this issue as I dont use this anymore

**Comment by reze-dev** [comment]
Closing this
